// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbaouxhsajpeegrrvlag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJiYW91eGhzYWpwZWVncnJ2bGFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMzU5NDAsImV4cCI6MjA2MzYxMTk0MH0._sxG22xNQSVeiPXuaAyfjwL0HCMBKry77LRzy7g8E6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);